######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 01:35:37 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
